// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/family-tree-redesign/Branching.tsx": () => import("../components/mockups/family-tree-redesign/Branching.tsx"),
  "./components/mockups/family-tree-redesign/Current.tsx": () => import("../components/mockups/family-tree-redesign/Current.tsx")
};
